//export const FETCH_RECIPE_INIT = "FETCH_RECIPE_INIT";
export const FETCH_RESULT_RECIPE_SUCCESS = 'FETCH_RESULT_RECIPE_SUCCESS';
export const FETCH_RESULT_RECIPE_FAIL = 'FETCH_RESULT_RECIPE_FAIL';
export const FETCH_RESULT_RECIPE_START = 'FETCH_RESULT_RECIPE_START';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';
export const FETCH_RECIPE_FAIL = 'FETCH_RECIPE_FAIL';
export const FETCH_RECIPE_START = 'FETCH_RECIPE_START';

export const ADD_NEW_RECIPE_START = 'ADD_NEW_RECIPE_START';
export const ADD_NEW_RECIPE_FAIL = 'ADD_NEW_RECIPE_FAIL';
export const ADD_NEW_RECIPE_SUCCESS = 'ADD_NEW_RECIPE_SUCCESS';

export const LOAD_UPDATE_SERVINGS = 'LOAD_UPDATE_SERVINGS';

export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const SET_BOOMARKED = 'SET_BOOMARKED';
export const REMOVE_BOOKMARK_WIDTH_ID = 'REMOVE_BOOKMARK_WIDTH_ID';
