//export const FETCH_RECIPE_INIT = "FETCH_RECIPE_INIT";
export const FETCH_RECIPE_SUCCESS = "FETCH_RECIPE_SUCCESS";
export const FETCH_RECIPE_FAIL = "FETCH_RECIPE_FAIL";
export const FETCH_RECIPE_START = "FETCH_RECIPE_START";
